rm(list = ls())
library(ggplot2)
library(RCurl)
library(plyr)
library(jsonlite)
library(reshape2)
library(scales)

handle <-
  getCurlHandle(
    httpheader = list(
      Accept = 'application/json, text/javascript, */*; q=0.01',
      'Accept-Ecoding' = 'gzip, deflate',
      'Accept-Language' = 'zh-CN,zh;q=0.9',
      Connection = 'keep-alive',
      # 'Content-Length' = '',
      'Content-Type' = 'application/x-www-form-urlencoded; charset=UTF-8',
      Cookie = 'theme=theme_base; userName=%E6%9D%8E%E9%95%BF%E5%85%B4; token=a25b085949531e494c422dccc17638b6; userId=s00580; userType=CBUSER',
      Referer = 'http://172.18.32.14:8080/ncc-oms/repayapply/repayApplyPage?token=a25b085949531e494c422dccc17638b6&userId=s00580&userType=CBUSER&userName=%E6%9D%8E%E9%95%BF%E5%85%B4',
      Host = '172.18.32.14:8080',
      'X-Requested-With' = 'XMLHttpRequest'
    )
  )



    form <- c(
      'draw'='1',
      'columns[0][data]'=' cApplyId',
      'columns[0][name]'=' ',
      'columns[0][searchable]'=' true',
      'columns[0][orderable]'=' false',
      'columns[0][search][value]'=' ',
      'columns[0][search][regex]'=' false',
      'columns[1][data]'=' repayReqId',
      'columns[1][name]'=' ',
      'columns[1][searchable]'=' true',
      'columns[1][orderable]'=' true',
      'columns[1][search][value]'=' ',
      'columns[1][search][regex]'=' false',
      'columns[2][data]'=' custNo',
      'columns[2][name]'=' ',
      'columns[2][searchable]'=' true',
      'columns[2][orderable]'=' false',
      'columns[2][search][value]'=' ',
      'columns[2][search][regex]'=' false',
      'columns[3][data]'=' custName',
      'columns[3][name]'=' ',
      'columns[3][searchable]'=' true',
      'columns[3][orderable]'=' false',
      'columns[3][search][value]'=' ',
      'columns[3][search][regex]'=' false',
      'columns[4][data]'=' idType',
      'columns[4][name]'=' ',
      'columns[4][searchable]'=' true',
      'columns[4][orderable]'=' true',
      'columns[4][search][value]'=' ',
      'columns[4][search][regex]'=' false',
      'columns[5][data]'=' idNo',
      'columns[5][name]'=' ',
      'columns[5][searchable]'=' true',
      'columns[5][orderable]'=' false',
      'columns[5][search][value]'=' ',
      'columns[5][search][regex]'=' false',
      'columns[6][data]'=' repayType',
      'columns[6][name]'=' ',
      'columns[6][searchable]'=' true',
      'columns[6][orderable]'=' true',
      'columns[6][search][value]'=' ',
      'columns[6][search][regex]'=' false',
      'columns[7][data]'=' repayMethod',
      'columns[7][name]'=' ',
      'columns[7][searchable]'=' true',
      'columns[7][orderable]'=' true',
      'columns[7][search][value]'=' ',
      'columns[7][search][regex]'=' false',
      'columns[8][data]'=' channelId',
      'columns[8][name]'=' ',
      'columns[8][searchable]'=' true',
      'columns[8][orderable]'=' true',
      'columns[8][search][value]'=' ',
      'columns[8][search][regex]'=' false',
      'columns[9][data]'=' bankCardNo',
      'columns[9][name]'=' ',
      'columns[9][searchable]'=' true',
      'columns[9][orderable]'=' false',
      'columns[9][search][value]'=' ',
      'columns[9][search][regex]'=' false',
      'columns[10][data]'=' mobile',
      'columns[10][name]'=' ',
      'columns[10][searchable]'=' true',
      'columns[10][orderable]'=' false',
      'columns[10][search][value]'=' ',
      'columns[10][search][regex]'=' false',
      'columns[11][data]'=' bankCode',
      'columns[11][name]'=' ',
      'columns[11][searchable]'=' true',
      'columns[11][orderable]'=' false',
      'columns[11][search][value]'=' ',
      'columns[11][search][regex]'=' false',
      'columns[12][data]'=' bankName',
      'columns[12][name]'=' ',
      'columns[12][searchable]'=' true',
      'columns[12][orderable]'=' false',
      'columns[12][search][value]'=' ',
      'columns[12][search][regex]'=' false',
      'columns[13][data]'=' totalAmt',
      'columns[13][name]'=' ',
      'columns[13][searchable]'=' true',
      'columns[13][orderable]'=' false',
      'columns[13][search][value]'=' ',
      'columns[13][search][regex]'=' false',
      'columns[14][data]'=' totalPeriod',
      'columns[14][name]'=' ',
      'columns[14][searchable]'=' true',
      'columns[14][orderable]'=' false',
      'columns[14][search][value]'=' ',
      'columns[14][search][regex]'=' false',
      'columns[15][data]'=' status',
      'columns[15][name]'=' ',
      'columns[15][searchable]'=' true',
      'columns[15][orderable]'=' true',
      'columns[15][search][value]'=' ',
      'columns[15][search][regex]'=' false',
      'columns[16][data]'=' statusRemark',
      'columns[16][name]'=' ',
      'columns[16][searchable]'=' true',
      'columns[16][orderable]'=' false',
      'columns[16][search][value]'=' ',
      'columns[16][search][regex]'=' false',
      'columns[17][data]'=' stepStatus',
      'columns[17][name]'=' ',
      'columns[17][searchable]'=' true',
      'columns[17][orderable]'=' true',
      'columns[17][search][value]'=' ',
      'columns[17][search][regex]'=' false',
      'columns[18][data]'=' repayStatus',
      'columns[18][name]'=' ',
      'columns[18][searchable]'=' true',
      'columns[18][orderable]'=' true',
      'columns[18][search][value]'=' ',
      'columns[18][search][regex]'=' false',
      'columns[19][data]'=' channelReqId',
      'columns[19][name]'=' ',
      'columns[19][searchable]'=' true',
      'columns[19][orderable]'=' false',
      'columns[19][search][value]'=' ',
      'columns[19][search][regex]'=' false',
      'columns[20][data]'=' channelRepayId',
      'columns[20][name]'=' ',
      'columns[20][searchable]'=' true',
      'columns[20][orderable]'=' false',
      'columns[20][search][value]'=' ',
      'columns[20][search][regex]'=' false',
      'columns[21][data]'=' channelRspId',
      'columns[21][name]'=' ',
      'columns[21][searchable]'=' true',
      'columns[21][orderable]'=' false',
      'columns[21][search][value]'=' ',
      'columns[21][search][regex]'=' false',
      'columns[22][data]'=' repayDate',
      'columns[22][name]'=' ',
      'columns[22][searchable]'=' true',
      'columns[22][orderable]'=' true',
      'columns[22][search][value]'=' ',
      'columns[22][search][regex]'=' false',
      'columns[23][data]'=' transDate',
      'columns[23][name]'=' ',
      'columns[23][searchable]'=' true',
      'columns[23][orderable]'=' true',
      'columns[23][search][value]'=' ',
      'columns[23][search][regex]'=' false',
      'columns[24][data]'=' excProcessCnt',
      'columns[24][name]'=' ',
      'columns[24][searchable]'=' true',
      'columns[24][orderable]'=' true',
      'columns[24][search][value]'=' ',
      'columns[24][search][regex]'=' false',
      'columns[25][data]'=' responseCode',
      'columns[25][name]'=' ',
      'columns[25][searchable]'=' true',
      'columns[25][orderable]'=' false',
      'columns[25][search][value]'=' ',
      'columns[25][search][regex]'=' false',
      'columns[26][data]'=' responseInfo',
      'columns[26][name]'=' ',
      'columns[26][searchable]'=' true',
      'columns[26][orderable]'=' false',
      'columns[26][search][value]'=' ',
      'columns[26][search][regex]'=' false',
      'columns[27][data]'=' transSeqno',
      'columns[27][name]'=' ',
      'columns[27][searchable]'=' true',
      'columns[27][orderable]'=' true',
      'columns[27][search][value]'=' ',
      'columns[27][search][regex]'=' false',
      'columns[28][data]'=' requestDatetime',
      'columns[28][name]'=' ',
      'columns[28][searchable]'=' true',
      'columns[28][orderable]'=' true',
      'columns[28][search][value]'=' ',
      'columns[28][search][regex]'=' false',
      'columns[29][data]'=' responseDatetime',
      'columns[29][name]'=' ',
      'columns[29][searchable]'=' true',
      'columns[29][orderable]'=' true',
      'columns[29][search][value]'=' ',
      'columns[29][search][regex]'=' false',
      'columns[30][data]'=' version',
      'columns[30][name]'=' ',
      'columns[30][searchable]'=' true',
      'columns[30][orderable]'=' false',
      'columns[30][search][value]'=' ',
      'columns[30][search][regex]'=' false',
      'columns[31][data]'=' remark',
      'columns[31][name]'=' ',
      'columns[31][searchable]'=' true',
      'columns[31][orderable]'=' false',
      'columns[31][search][value]'=' ',
      'columns[31][search][regex]'=' false',
      'columns[32][data]'=' createDatetime',
      'columns[32][name]'=' ',
      'columns[32][searchable]'=' true',
      'columns[32][orderable]'=' true',
      'columns[32][search][value]'=' ',
      'columns[32][search][regex]'=' false',
      'columns[33][data]'=' updateDatetime',
      'columns[33][name]'=' ',
      'columns[33][searchable]'=' true',
      'columns[33][orderable]'=' true',
      'columns[33][search][value]'=' ',
      'columns[33][search][regex]'=' false',
      'order[0][column]'='33',
      'order[0][dir]'=' desc',
      'start'='0',
      'length'='20',
      'search[value]'=' ',
      'search[regex]'=' false',
      'startCreateDatetime'=' 2018-09-22 00:00:00',
      'endCreateDatetime'=' 2018-09-29 23:59:59'
      
      
    )
    res <- postForm(
      uri = 'http://172.18.32.14:8080/ncc-oms/repay_reform/repayChannelInfo/listPage',
      style = 'POST',
      curl = handle,
      .params = form
    )



get_res <-
  getdata(start_time,
          end_time,
          start_num,
          length,
          handle,
          draw)

json_result <- fromJSON(get_res)
response_code <- json_result$code
total <- json_result$total
tmp <- json_result$rows
result <- rbind(result, tmp)
loop_time <- total %/% length + ifelse(total %% length > 0, 1, 0)
cat('共', total, '条数据，分', loop_time, '次完成，目前为第1次')
if (loop_time > 1) {
  for (i in 1:(loop_time - 1)) {
    draw <- as.character(i)
    start_num <- i * length
    get_res <-
      getdata(start_time, end_time, start_num, length, handle, draw,trans_type )
    json_result <- fromJSON(get_res)
    response_code <- json_result$code
    total <- json_result$total
    tmp <- json_result$rows
    result <- rbind(result, tmp)
    cat('共', total, '条数据，分', loop_time, '次完成，目前为第', i + 1, '次\n')
    Sys.sleep(1)
  }
}
cat('数据下载完成\n')